audio_representation_layers: 3
audio_split_samples: 1000
batch_size: 100
clip: 1
cross_attention_layers: 2
data: {path: /content/ProgrammingInterview/data, train_file: train_data.csv, valid_file: valid_data.csv,
  wavs_location: /content/task_data/}
dropout: 0.2
epochs: 100
hid_dim: 256
log_path: /content/ProgrammingInterview/runs/weighted_loss/2021-06-01 10:35:28
mode: weighted_loss
model_name: multimodal-multilabel-model.pt
n_heads: 8
optimizer: {beta1: 0.9, beta2: 0.999, lr: 0.0005, type: Adam}
pf_dim: 512
positional_encoding_max_len: 5000
text_representation_layers: 2
